import { sidebar } from "vuepress-theme-hope";

export const zhSidebar = sidebar({
  "/zh/": ["", "router.md", "changelog.md", "intro.md"],
  "/zh/posts/": "structure",
  "/zh/dev-rpc-thrift/": "structure",
  "/zh/demo-record/demo-microk8s/": "structure",
"/zh/dev-algorithm-datastructure": "structure",
  "/zh/dev-java-commonsense/": "structure",
  "/zh/dev-java-log/": "structure",
  "/zh/dev-java-schedule/": "structure",
  "/zh/dev-java-test/": "structure",
  "/zh/dev-java-maven/": "structure",
  "/zh/dev-java-xml/": "structure",
  "/zh/dev-java-crud/": "structure",
  "/zh/dev-java-office/": "structure",
  "/zh/dev-java-spring/": "structure",
  "/zh/dev-java-springcloud/": "structure",
  "/zh/dev-java-cache/": "structure",
  "/zh/dev-java-event/": "structure",
  "/zh/ops-terminal-shell/": "structure",
  "/zh/ops-hw-red/": "structure",
  "/zh/ops-cicd-jenkins/": "structure",
  "/zh/z-security-vulnerability/": "structure",
});
