spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mydb;
    username: sa
    password: password
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(-){faint} %clr([%14.14t]){faint} %clr(%-40.40logger.%13.13M){cyan} %clr(%3.3L) %clr(:){faint} %msg%n"
  level:
    org:
      springframework:
        boot:
          diagnostics: debug
        jdbc: debug
    org.mybatis: debug
    java.sql: debug
    org.example.mapper: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl