server.port=9300
spring.application.name=xx-config

# \u5B58\u5230git\u4E2D\u5FC3
#spring.cloud.config.server.git.uri=http://github.com/xxx/xxx.git
#spring.cloud.config.server.git.search-paths=config-center
#spring.cloud.config.server.git.username=xxx
#spring.cloud.config.server.git.passphrase=123321
# \u5B58\u5230\u672C\u5730
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:./xx-config/config-repo
