server.port=9300
spring.application.name=xx-config

# \u6253\u5F00\u6240\u6709\u7684web\u8BBF\u95EE\u7AEF\u70B9
management.endpoints.web.exposure.include=*

##############
# \u914D\u7F6E\u4E2D\u5FC3
##############
# \u5B58\u5230git\u4E2D\u5FC3
#spring.cloud.config.server.git.uri=http://github.com/xxx/xxx.git
#spring.cloud.config.server.git.search-paths=config-center
#spring.cloud.config.server.git.username=xxx
#spring.cloud.config.server.git.passphrase=123321
# \u5B58\u5230\u672C\u5730
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:./xx-config/config-repo

# \u6D88\u606F\u961F\u5217
spring.cloud.bus.enabled=true
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

