spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.229.121.30:3306/blogdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    

server:
  port: 8088
    
logging:
  level: 
    root: info 
    com.cy: info
