################################
#
#        mybatis-plus
# 
################################
mybatis-plus:
  #vo可写全名
  type-aliases-package: com.cy.myblog.pojo.* 
  mapper-locations:
  - classpath:/mapper/**/*.xml
  configuration:
    #暂时不要缓存
    cache-enabled: true
    #下划线转驼峰    map-underscore-to-camel-case: true 
    
    
################################
#
#        spring - mvc
# 
################################
server:
  servlet:
    # 项目路径名
    context-path: /


spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/pages
    suffix: .html
  profiles:
    active: dev
    
    
################################
#
#        log
# 
################################
logging:
  level: 
    root: info 
    com.cy: debug
    
    
    
    
################################
#
#        自定义
# 
################################
page:
  config: 
    pageSize: 2
