spring:
  profiles:
    active: dev
#  freemarker:#    template-loader-path:#    - classpath:/templates/pages
#    suffix: .html
  thymeleaf:
    cache: false
    prefix: classpath:/templates/pages
    suffix: .html

mybatis:
  mapper-locations:
  - classpath:mapper/*/*.xml 



