#mybatis-plus
mybatis-plus:
  configuration:
    #暂时不要缓存
    cache-enabled: false
    #下划线转驼峰    map-underscore-to-camel-case: true 
  #vo可写全名
  type-aliases-package: com.cy.myblog.pojo.* 
  mapper-locations:
  - classpath:/mapper/**/*.xml
    

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/pages
    suffix: .html
    servlet:
      content-type: text/html; charset=utf-8   profiles:
    active: dev
  mvc:
    favicon:
      enabled: false   
#  freemarker:#    template-loader-path:#    - classpath:/templates/pages
#    suffix: .html



