<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.example</groupId>
        <artifactId>xx-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../xx-parent/pom.xml</relativePath>
    </parent>

    <artifactId>xx-config</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-server</artifactId>
        </dependency>

        <!--
        说明：
        当配置了 mq 和 actuator 之后，可以调用 actuator 的
            /actuator/bus-refresh/ —— 全局
            /actuator/bus-refresh/ —— 指定服务
        接口，来通知全局/指定服务的配置刷新。
        这套解决方案比较多“显而易见”的问题，就不多尝试了。
        + 权限平等，任何一个完成上述服务理论上都可以通知全部服务刷新配置。只能通过运维人工管理使其“有序”。
        + 维护成本高，需要维护多个服务。
        -->
        <!-- AMQP（Advanced Message Queuing Protocol，高级消息队列协议） -->
<!--        <dependency>-->
<!--            <groupId>org.springframework.cloud</groupId>-->
<!--            <artifactId>spring-cloud-starter-bus-amqp</artifactId>-->
<!--        </dependency>-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>