# \u4EC5\u5728 dev \u73AF\u5883\u751F\u6548\u7684 H2 \u914D\u7F6E
spring.datasource.url=jdbc:h2:mem:goodsdb;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# \u81EA\u52A8\u521D\u59CB\u5316\u811A\u672C
spring.datasource.schema=classpath:db/schema.sql
spring.datasource.initialization-mode=always

# \u5F00\u542F H2 \u63A7\u5236\u53F0
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console