spring.datasource.username={cipher}1c60465adf6d1c719a1444396e97760dcdad338b3d40cf9f62bb8fe462adb297
spring.datasource.password={cipher}93da48e7a407da912eeedafb4bf88890ea954bfeafc8c36c5287e7ec4d87732f
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://192.168.10.128:3306/goodsdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false

# \u751F\u4EA7\u73AF\u5883\u901A\u5E38\u5173\u95ED\u81EA\u52A8\u521D\u59CB\u5316\u811A\u672C
spring.datasource.initialization-mode=never
