# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /api

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages

token:
  # 令牌自定义标识
  header: Authorization
  # 令牌有效期（默认30分钟）
  expireTime: 30
  # 令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: org.example.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# 日志配置
logging:
  level:
    org.example: info
    org.springframework: warn
